name: venv_audio_curiosity_conda_tf
dependencies:
  - python=3.7
  - pip
  - anaconda
  - ffmpeg
  - tensorflow-gpu==1.15.0
  - conda-forge::libsndfile
  - pip:
    - gym[atari]
    - gym-retro
    - baselines
    - numpy
    - scipy
    - mpi4py
    - Pillow==2.2.1
    - librosa
